# Generated by Django 4.1.1 on 2022-09-12 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20220812_2022'),
        ('webapp', '0013_comment_article_comment_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='user',
            field=models.ManyToManyField(related_name='likes', to='accounts.profile'),
        ),
    ]
