# Generated by Django 4.1.1 on 2022-09-16 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0016_alter_article_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='user',
            new_name='likes',
        ),
    ]
